[package]
name = "kifuwarabe_movement"
version = "0.1.0"
authors = ["muzudho <muzudho1@gmail.com>"]

[dependencies]
lazy_static = "1.1.0"

[dependencies.kifuwarabe_position]
git = "https://github.com/muzudho/rust_kifuwarabe_position.git"
rev = "8956e8b019be11e85ac4fee4d75b7602d5e7fc21"
